### ISSUE TITLE
Ability to favorite locations

### ISSUE THREAD

**Issue by warpling** [daneden/Solstice#62]
…or see recent searches :)
I often check myself compared to family and friends around the world ☀️

**Comment by daneden** [comment]
Hey @warpling! I'm pleased to report that the latest major release of Solstice adds the ability to save multiple locations, as well as a host of other improvements. Please download the latest update from the App Store and let me know if you have any other feedback!

**Comment by warpling** [comment]
Very cool! Thanks for letting me know!!
