### ISSUE TITLE
Apple Watch app shows wrong times until restarted after daylight savings time change

### ISSUE THREAD

**Issue by peterjcole** [daneden/Solstice#67]
I had the Apple Watch app already open before the recent UK daylight savings change. Looking at the watch app this afternoon, the sunset time was an hour behind (it was saying around 5:30 instead of 4:30). The position on the sun graph was also wrong.

The complication sunset time on my watch face was correct already.

I closed the watch app using the recent apps menu & swiping, when I reopened it the time was correct.

Didn't think to take a screenshot. Sorry about that!

Thanks, love the app!

**Comment by daneden** [comment]
Hey @peterjcole, thanks for submitting this bug report! I recently rewrote most of Solstice's codebase for the v2 release, which is now available on the App Store. Please download the latest version and let me know if you continue to experience this issue!
