### ISSUE TITLE
Attempting to manually select city without sunrise and sunset causes the app to crash

### ISSUE THREAD

**Issue by lognseth** [daneden/Solstice#69]
Running iOS 16.3 the app crashes and exits when I manually attempt to select Longyearbyen, Barentsburg or any other city that currently has no sunrise or sunset due to the polar night.

**Comment by daneden** [comment]
Hey @lognseth! I'm pleased to report that this should no longer be an issue in v2.0, which just became available on the App Store. Please download the update and let me know if you continue to experience this issue or have any other feedback.
