### ISSUE TITLE
Countdown Watch Widget Never Updates

### ISSUE THREAD

**Issue by ssnkhan** [daneden/Solstice#79]
Hello,

The “Countdown” widget never appears to render, remaining as a placeholder consisting of a square and line. Latest versions of iOS 15, on Ultra. Thanks!

**Comment by daneden** [comment]
Thanks for filing this bug @ssnkhan! I’ve found a fix that is planned for v2.2. Closing this issue as a duplicate of #90, where progress will be updated.
